export const data = [
  {
    id: 1,
    name: "A.N.C.A ANTI-NEUTROFILOS",
    sample: "suero",
    method: "IFI - Inmunofluorescencia Indirecta",
    price1: 180,
    price2: 150,
    tube: "tapa rojo ó amarillo",
    info: "se sugiere ayuno de 8 hras",
    time: "6 días",
    quantity: 1,
  },
  {
    id: 2,
    name: "acido folico",
    sample: "suero",
    method: "quimioluminiscencia",
    price1: 75,
    price2: 50,
    tube: "tapa rojo ó amarillo",
    info: "se sugiere ayuno de 8 hras",
    time: "1 día",
    quantity: 1,
  },
  {
    id: 3,
    name: "aga y electrolitos (a domicilio)",
    sample: "sangre arterial",
    method: "gasometria",
    price1: 150,
    price2: 100,
    tube: "jeringa especial con heparina",
    info: "no requiere ayuno previo",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 4,
    name: "alfafeto proteina(afp)",
    sample: "suero",
    method: "quimioluminiscencia",
    price1: 60,
    price2: 40,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 hras",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 5,
    name: "amilasa serica",
    sample: "suero",
    method: "cinetico",
    price1: 25,
    price2: 12,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 6,
    name: "ANTI DNA-DS",
    sample: "suero",
    method: "IFI - Inmunofluorescencia Indirecta",
    price1: 160,
    price2: 130,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "10 días",
    quantity: 1,
  },
  {
    id: 7,
    name: "ANTI-CCP(PEPTIDO CICLICO CITRUNILADO)IGG",
    sample: "suero",
    method: "elisa",
    price1: 250,
    price2: 220,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "8 días",
    quantity: 1,
  },
  {
    id: 8,
    name: "ANTICUERPOS ANTINUCLEARES(ANA)",
    sample: "suero",
    method: "clia",
    price1: 150,
    price2: 120,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "6 días",
    quantity: 1,
  },
  {
    id: 9,
    name: "ANTICUERPOS ANTITIROIDES",
    sample: "suero",
    method: "ECLIA / MODULAR PE",
    price1: 150,
    price2: 130,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "5 dias",
    quantity: 1,
  },
  {
    id: 10,
    name: "ANTIGENO CARCINO EMBRIONARIO(CEA)",
    sample: "suero",
    method: "quimioluminiscencia",
    price1: 70,
    price2: 40,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 día",
    quantity: 1,
  },
  {
    id: 11,
    name: "CA 125(ovario)",
    sample: "suero",
    method: "quimioluminiscencia",
    price1: 70,
    price2: 40,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 día",
    quantity: 1,
  },
  {
    id: 12,
    name: "CA 15-3(mama)",
    sample: "suero",
    method: "quimioluminiscencia",
    price1: 75,
    price2: 40,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 día",
    quantity: 1,
  },
  {
    id: 13,
    name: "glucosa",
    sample: "suero",
    method: "colorimetrico",
    price1: 10,
    price2: 6,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 14,
    name: "colesterol total",
    sample: "suero",
    method: "colorimetrico",
    price1: 10,
    price2: 6,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 15,
    name: "trigliceridos",
    sample: "suero",
    method: "colorimetrico",
    price1: 15,
    price2: 7,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 16,
    name: "hemograma completo automatizada",
    sample: "sangre total",
    method: "citometría de flujo",
    price1: 30,
    price2: 15,
    tube: "tapa lila",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 17,
    name: "hemoglobina",
    sample: "sangre total",
    method: "manual",
    price1: 10,
    price2: 5,
    tube: "tapa lila",
    info: "no requiere ayuno",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 18,
    name: "examen completo de orina(eco)",
    sample: "orina ocasional",
    method: "manual",
    price1: 15,
    price2: 7,
    tube: "frasco tapa rojo no esteril",
    info: "se recomienda primera orina de la mañana chorro intermedio ",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 19,
    name: "hemoglobina glicosilada(HbA1c)",
    sample: "sangre total",
    method: "inmunoflorescencia",
    price1: 70,
    price2: 40,
    tube: "tapa lila",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 20,
    name: "tsh",
    sample: "suero",
    method: "quimioluminiscencia",
    price1: 70,
    price2: 40,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 21,
    name: "t4 libre",
    sample: "suero",
    method: "quimioluminiscencia",
    price1: 70,
    price2: 40,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 22,
    name: "t3 libre",
    sample: "suero",
    method: "quimioluminiscencia",
    price1: 70,
    price2: 40,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 23,
    name: "perfil lipidico",
    sample: "suero",
    method: "colorimetrico",
    price1: 40,
    price2: 28,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 24,
    name: "perfil hepatico",
    sample: "suero",
    method: "cinetico/colorimetrico",
    price1: 50,
    price2: 30,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 25,
    name: "perfil renal simple",
    sample: "suero",
    method: "cinetico/colorimetrico",
    price1: 35,
    price2: 19,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 26,
    name: "perfil tiroideo(tsh-t4 libre-t3)",
    sample: "suero",
    method: "quimioluminiscencia",
    price1: 180,
    price2: 115,
    tube: "tapa rojo ó amarillo",
    info: "se sugiere ayuno de 8 hras",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 27,
    name: "CREATINFOSFOQUINASA (CPK TOTAL)",
    sample: "suero",
    method: "cinetico",
    price1: 50,
    price2: 38,
    tube: "tapa rojo ó amarillo",
    info: "se sugiere ayuno de 8 hras",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 28,
    name: "	PROLACTINA POOL",
    sample: "suero",
    method: "quimioluminiscencia",
    price1: 120,
    price2: 75,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HRS. NO EJERCICIOS, EVITAR ESTADOS DE ESTRES. (30 MINUTOS DE REPOSO ANTES DE LA TOMA DE MUESTRA) INCLUYE 03 TOMAS CADA 15 MINUTOS, SALVO OTRA INDICACION DEL MÉDICO TRATANTE.",
    time: "1 horas",
    quantity: 1,
  },
  {
    id: 29,
    name: "	BIOPSIA PIEZA OPERATORIA <= 1 MM. (L7)",
    sample: "BIOPSIA",
    method: "MICROSCOPIA / MANUAL",
    price1: 150,
    price2: 80,
    tube: "MEDIO CON FORMOL",
    info: "LA MUESTRA DEBE COLOCARSE INMEDIATAMENTE EN UN CONTENEDOR CON FORMOL AL 10% DE TAL MANERA QUE ESTA CUBRA TODA LA MUESTRA Y CERRAR HERMETICAMENTE.NO DEBE SER MAYOR A 5MM, OBLIGATORIO: ORDEN MEDICA CON DETALLE DE ZONA + FIRMA Y SELLO",
    time: "7 días",
    quantity: 1,
  },
  {
    id: 30,
    name: "prolactina",
    sample: "suero",
    method: "elisa",
    price1: 70,
    price2: 40,
    tube: "tapa rojo ó amarillo",
    info: "se sugiere ayuno de 8 hras",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 31,
    name: "lh",
    sample: "suero",
    method: "inmunoflorescencia",
    price1: 70,
    price2: 40,
    tube: "tapa rojo ó amarillo",
    info: "se sugiere ayuno de 8 hras",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 32,
    name: "fsh",
    sample: "suero",
    method: "quimioluminiscencia",
    price1: 70,
    price2: 40,
    tube: "tapa rojo ó amarillo",
    info: "se sugiere ayuno de 8 hras",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 33,
    name: "testosterona total",
    sample: "suero",
    method: "quimioluminiscencia",
    price1: 70,
    price2: 40,
    tube: "tapa rojo ó amarillo",
    info: "se sugiere ayuno de 8 hras",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 34,
    name: "testosterona libre",
    sample: "suero",
    method: "quimioluminiscencia",
    price1: 75,
    price2: 48,
    tube: "tapa rojo ó amarillo",
    info: "se sugiere ayuno de 8 hras",
    time: "1 día",
    quantity: 1,
  },
  {
    id: 35,
    name: "estradiol-e2",
    sample: "suero",
    method: "quimioluminiscencia",
    price1: 70,
    price2: 40,
    tube: "tapa rojo ó amarillo",
    info: "se sugiere ayuno de 8 hras",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 36,
    name: "progesterona",
    sample: "suero",
    method: "quimioluminiscencia",
    price1: 70,
    price2: 40,
    tube: "tapa rojo ó amarillo",
    info: "se sugiere ayuno de 8 hras",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 37,
    name: "troponina i",
    sample: "suero",
    method: "inmunoflorescencia",
    price1: 60,
    price2: 45,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hota",
    quantity: 1,
  },
  {
    id: 38,
    name: "lipasa",
    sample: "suero",
    method: "cinetico",
    price1: 40,
    price2: 25,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 39,
    name: "ggt-gamma-glutamil",
    sample: "suero",
    method: "cinetico",
    price1: 40,
    price2: 25,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 40,
    name: "calcio serico",
    sample: "suero",
    method: "colorimetrico",
    price1: 25,
    price2: 15,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 41,
    name: "acido urico",
    sample: "suero",
    method: "colorimetrico",
    price1: 15,
    price2: 7,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 42,
    name: "perfil de coagulacion(tp-ttpa-tc-ts)",
    sample: "plasma/citrato",
    method: "coagulometria",
    price1: 45,
    price2: 28,
    tube: "tapa celeste",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 43,
    name: "grupo sanguineo",
    sample: "sangre total",
    method: "manual",
    price1: 10,
    price2: 7,
    tube: "tapa lila",
    info: "no requiere ayuno previo",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 44,
    name: "heces seriado x 3 veces",
    sample: "heces",
    method: "microscopia",
    price1: 25,
    price2: 15,
    tube: "frasco tapa rosca",
    info: "MUESTRA FRESCA, LA QUE CONTENGA MOCO Y/O SANGRE. CANTIDAD: = NUEZ. INFANTES: EL PAÑAL COLOCAR AL REVES, PARA EVITAR QUE EL GEL DEL PAÑAL ABSORBA LOS LIQUIDOS O QUE LAS HECES SE IMPREGNEN",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 45,
    name: "heces simple x 1 veces",
    sample: "heces",
    method: "microscopia",
    price1: 10,
    price2: 5,
    tube: "frasco tapa rosca",
    info: "MUESTRA FRESCA, LA QUE CONTENGA MOCO Y/O SANGRE. CANTIDAD: = NUEZ. INFANTES: EL PAÑAL COLOCAR AL REVES, PARA EVITAR QUE EL GEL DEL PAÑAL ABSORBA LOS LIQUIDOS O QUE LAS HECES SE IMPREGNEN",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 46,
    name: "heces coprofuncional",
    sample: "heces",
    method: "microscopia",
    price1: 25,
    price2: 15,
    tube: "frasco tapa rosca",
    info: "MUESTRA FRESCA, LA QUE CONTENGA MOCO Y/O SANGRE. CANTIDAD: = NUEZ. INFANTES: EL PAÑAL COLOCAR AL REVES, PARA EVITAR QUE EL GEL DEL PAÑAL ABSORBA LOS LIQUIDOS O QUE LAS HECES SE IMPREGNEN",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 47,
    name: "metodo de faust-heces concentrada",
    sample: "heces",
    method: "microscopia",
    price1: 20,
    price2: 12,
    tube: "frasco tapa rosca",
    info: "MUESTRA FRESCA, LA QUE CONTENGA MOCO Y/O SANGRE. CANTIDAD: = NUEZ. INFANTES: EL PAÑAL COLOCAR AL REVES, PARA EVITAR QUE EL GEL DEL PAÑAL ABSORBA LOS LIQUIDOS O QUE LAS HECES SE IMPREGNEN",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 48,
    name: "metodo de baermann-strongyloides",
    sample: "heces",
    method: "microscopia",
    price1: 20,
    price2: 12,
    tube: "frasco tapa rosca",
    info: "MUESTRA FRESCA, LA QUE CONTENGA MOCO Y/O SANGRE. CANTIDAD: = NUEZ. INFANTES: EL PAÑAL COLOCAR AL REVES, PARA EVITAR QUE EL GEL DEL PAÑAL ABSORBA LOS LIQUIDOS O QUE LAS HECES SE IMPREGNEN",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 49,
    name: "reaccion inflamatoria-heces",
    sample: "heces",
    method: "microscopia",
    price1: 10,
    price2: 5,
    tube: "frasco tapa rosca",
    info: "MUESTRA FRESCA, LA QUE CONTENGA MOCO Y/O SANGRE. CANTIDAD: = NUEZ. INFANTES: EL PAÑAL COLOCAR AL REVES, PARA EVITAR QUE EL GEL DEL PAÑAL ABSORBA LOS LIQUIDOS O QUE LAS HECES SE IMPREGNEN",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 50,
    name: "thevenon-heces-sangre oculta",
    sample: "heces",
    method: "manual",
    price1: 15,
    price2: 8,
    tube: "frasco tapa rosca",
    info: "MUESTRA FRESCA, LA QUE CONTENGA MOCO Y/O SANGRE. CANTIDAD: = NUEZ. INFANTES: EL PAÑAL COLOCAR AL REVES, PARA EVITAR QUE EL GEL DEL PAÑAL ABSORBA LOS LIQUIDOS O QUE LAS HECES SE IMPREGNEN",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 51,
    name: "tolerancia a la glucosa",
    sample: "suero",
    method: "bioquimica automatizada",
    price1: 50,
    price2: 35,
    tube: "tapa rojo ó amarillo",
    info: "MUESTRAS TOMADAS:BASAL 30, 60, 90, 120 MINUTOS. SALVO OTRA INDICACION DEL MEDICO. ADULTOS: 75 GR. glucosa anhidra Y  EMBARAZADAS SÓLO ENTRE 24 A 28 SEMANAS. REVISAR ORDEN MEDICA: 100 GR glucosa anhidra .. DISOLVER EN 250 - 300 ML DE AGUA",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 53,
    name: "lamina periferica",
    sample: "sangre total con edta",
    method: "microscopia/automatizado",
    price1: 60,
    price2: 35,
    tube: "tapa lila mas lamina",
    info: "TODA REFERENCIA: DEBE REALIZAR EXTENDIDO DE SANGRE SOBRE LÁMINA PORTAOBJETOS. ADEMÁS ENVIAR TUBO TAPA LILA.",
    time: "1 dia",
    quantity: 1,
  },
  {
    id: 54,
    name: "recuento de plaquetas en lamina",
    sample: "sangre total con edta",
    method: "microscopia/manual",
    price1: 15,
    price2: 8,
    tube: "tapa lila mas lamina",
    info: "TODA REFERENCIA: DEBE REALIZAR EXTENDIDO DE SANGRE SOBRE LÁMINA PORTAOBJETOS. ADEMÁS ENVIAR TUBO TAPA LILA.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 55,
    name: "espermatograma",
    sample: "semen",
    method: "microscopia/manual",
    price1: 60,
    price2: 35,
    tube: "frasco tapa verde esteril",
    info: "SE REQUIERE DE 3 A 5 DÍAS DE ABSTINENCIA. SE RECEPCIONAN LUNES A SÁBADO DE 7 AM A 11 AM. EN CASO DE FERIADO SE RECIBE UN DÍA ANTES. INDICAR FECHA DE VASECTOMÍA SI CORRESPONDE.",
    time: "2 días",
    quantity: 1,
  },
  {
    id: 56,
    name: "insulina",
    sample: "suero",
    method: "elisa",
    price1: 70,
    price2: 40,
    tube: "tapa rojo ó amarillo",
    info: "se sugiere ayuno de 8 hras",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 57,
    name: "dimero d",
    sample: "suero",
    method: "coagulacion",
    price1: 70,
    price2: 50,
    tube: "tapa rojo ó amarillo",
    info: "se sugiere ayuno de 8 hras",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 58,
    name: "ferritina",
    sample: "suero",
    method: "elisa",
    price1: 60,
    price2: 35,
    tube: "tapa rojo ó amarillo",
    info: "se sugiere ayuno de 8 hras",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 59,
    name: "procalcitonina agotado",
    sample: "suero",
    method: "inmunoflorescencia",
    price1: 110,
    price2: 90,
    tube: "tapa rojo ó amarillo",
    info: "se sugiere ayuno de 8 hras",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 60,
    name: "inmunoglobulina e (ige)",
    sample: "suero",
    method: "elisa",
    price1: 60,
    price2: 40,
    tube: "tapa rojo ó amarillo",
    info: "se sugiere ayuno de 8 hras",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 61,
    name: "cortisol am",
    sample: "suero",
    method: "quimioluminiscencia",
    price1: 60,
    price2: 50,
    tube: "tapa rojo ó amarillo",
    info: "MUESTRA TOMADA ENTRE 8:00 Y 9:00 AM. SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "1 día",
    quantity: 1,
  },
  {
    id: 62,
    name: "cortisol pm",
    sample: "suero",
    method: "quimioluminiscencia",
    price1: 60,
    price2: 50,
    tube: "tapa rojo ó amarillo",
    info: "MUESTRA TOMADA ENTRE 4:00 Y 5:00 pm. SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "1 día",
    quantity: 1,
  },
  {
    id: 63,
    name: "coombs directo",
    sample: "sangre total",
    method: "HEMAGLUTINACION / MANUAL",
    price1: 45,
    price2: 28,
    tube: "tapa lila",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 64,
    name: "coombs indirecto",
    sample: "suero",
    method: "HEMAGLUTINACION / MANUAL",
    price1: 50,
    price2: 28,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 65,
    name: "vih combo(CLIA)",
    sample: "suero",
    method: "quimioluminiscencia",
    price1: 65,
    price2: 35,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "1 día",
    quantity: 1,
  },
  {
    id: 66,
    name: "vih prueba rapida",
    sample: "suero",
    method: "cromatografia",
    price1: 45,
    price2: 25,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 67,
    name: "serologia cualitativa rpr-sifilis",
    sample: "suero",
    method: "floculacion/manual",
    price1: 15,
    price2: 10,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 68,
    name: "serologia semi-cuantitativa rpr-sifilis",
    sample: "suero",
    method: "floculacion/manual",
    price1: 25,
    price2: 15,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 69,
    name: "vitamina b12",
    sample: "suero",
    method: "elisa",
    price1: 70,
    price2: 55,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "1 día",
    quantity: 1,
  },
  {
    id: 70,
    name: "cpk-mb",
    sample: "suero",
    method: "inmunoflorescencia",
    price1: 60,
    price2: 40,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 71,
    name: "hdl colesterol",
    sample: "suero",
    method: "cinetico",
    price1: 20,
    price2: 15,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 72,
    name: "psa libre",
    sample: "suero",
    method: "quimioluminiscencia",
    price1: 75,
    price2: 55,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "1 día",
    quantity: 1,
  },
  {
    id: 73,
    name: "psa total",
    sample: "suero",
    method: "elisa",
    price1: 65,
    price2: 40,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "2 horas",
    quantity: 1,
  },
  {
    id: 74,
    name: "variante du",
    sample: "sangre total",
    method: "HEMAGLUTINACION / MANUAL",
    price1: 25,
    price2: 15,
    tube: "tapa lila",
    info: "no necesita ayuno previo.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 75,
    name: "CHLAMYDIA TRACHOMATIS IGM-igg",
    sample: "suero",
    method: "elisa",
    price1: 150,
    price2: 80,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "6 días",
    quantity: 1,
  },
  {
    id: 76,
    name: "ANTICOAGULANTE LUPICO ",
    sample: "suero",
    method: "COAGULOMETRICO",
    price1: 150,
    price2: 120,
    tube: "tapa celeste",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA, 3 tubos tapa celeste",
    time: "6 dias",
    quantity: 1,
  },
  {
    id: 77,
    name: "ANTI CARDIOLIPINA IGG-IGM",
    sample: "suero",
    method: "ELISA",
    price1: 180,
    price2: 150,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "7 dias",
    quantity: 1,
  },
  {
    id: 78,
    name: "BETA 2 GLICOPROTEINA I IGG-IGM",
    sample: "suero",
    method: "ELISA",
    price1: 180,
    price2: 170,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "8 dias",
    quantity: 1,
  },
  {
    id: 79,
    name: "tiempo de protrombina(tp) más inr",
    sample: "plasma/citrato",
    method: "coagulometria",
    price1: 15,
    price2: 15,
    tube: "tapa celeste",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 80,
    name: "tiempo de tromboplastina parcial activada(ttpa)",
    sample: "plasma/citrato",
    method: "coagulometria",
    price1: 15,
    price2: 10,
    tube: "tapa celeste",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 81,
    name: "retraccion de coagulo",
    sample: "sangre total",
    method: "optico-mecanico/manual",
    price1: 15,
    price2: 10,
    tube: "tubo sin aditivo",
    info: "no requiere preparacion previa. MUESTRA: MÍNIMO 3.0 ML DE SANGRE TOTAL (SIN NINGÚN ADITIVO), TRANSPORTAR DE INMEDIATO AL LABORATORIO PARA EL PRONTO PROCESO.",
    time: "3 horas",
    quantity: 1,
  },
  {
    id: 82,
    name: "microalbuminuria orina simple",
    sample: "orina simple",
    method: "inmunoflorescencia",
    price1: 60,
    price2: 40,
    tube: "frasco tapa rosca",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 83,
    name: "helicobacter pylori igg",
    sample: "suero",
    method: "quimioluminiscencia",
    price1: 60,
    price2: 40,
    tube: "tapa rojo/amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "3 horas",
    quantity: 1,
  },
  {
    id: 84,
    name: " recuento de reticulocitos",
    sample: "sangre total",
    method: "microscopia manual",
    price1: 25,
    price2: 15,
    tube: "tapa lila",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 85,
    name: "constantes corpusculares",
    sample: "sangre total",
    method: "manual",
    price1: 15,
    price2: 10,
    tube: "tapa lila",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 86,
    name: "OXIUROS (TEST DE GRAHAM)",
    sample: "CINTA ADHESIVA",
    method: "microscopia/manual",
    price1: 10,
    price2: 6,
    tube: "lamina",
    info: "LIMPIEZA DE LA ZONA ANAL ANTES DE ACOSTARSE. HORA DE TOMA DE MUESTRA : 5:00 A 6:00 AM MATERIALES: CINTA ADHESIVA TRANSPARENTE (1 A 2 X 10 A 12 CM) + LÁMINA PORTAOJETOS (LABORATORIO) PROCEDIMIENTO: COLOCAR AL PCTE. BOCA ABAJO EN LA POSICIÓN QUE PERMITA QUE LAS NALGAS SE SEPAREN PARA COLOCAR LA CINTA EN EL ANO ( AL CENTRO Y ALREDEDOR Ó PERI-ANAL) Y LUEGO COLOCARLO EN LA LAMINA.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 87,
    name: "ACIDOS BILIARES suiza lab (lima)",
    sample: "suero",
    method: "ELISA",
    price1: 180,
    price2: 150,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "5 dias",
    quantity: 1,
  },
  {
    id: 88,
    name: "HORMONA ANTI MULLERIANA (AMH/MIS)",
    sample: "suero",
    method: "ECLIA / COBAS 8000",
    price1: 250,
    price2: 230,
    tube: "tapa rojo ó amarillo",
    info: "NO REQUIERE AYUNO ANTES DE LA PRUEBA.",
    time: "5 dias",
    quantity: 1,
  },
  {
    id: 89,
    name: "ANTI CORE",
    sample: "suero",
    method: "elisa",
    price1: 60,
    price2: 45,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "1 día",
    quantity: 1,
  },
  {
    id: 90,
    name: "hepatitis b-antigeno de superficie (hbsag)",
    sample: "suero",
    method: "inmunocromatografia",
    price1: 35,
    price2: 25,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 91,
    name: "hepatitis a (igm)",
    sample: "suero",
    method: "inmunocromatografia",
    price1: 45,
    price2: 28,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 92,
    name: "hepatitis c (hcv)",
    sample: "suero",
    method: "inmunocromatografia",
    price1: 45,
    price2: 30,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 94,
    name: "urea",
    sample: "suero",
    method: "cinetico",
    price1: 10,
    price2: 6,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 95,
    name: "creatinina",
    sample: "suero",
    method: "cinetico",
    price1: 10,
    price2: 6,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 96,
    name: "proteinuria orina de 24 h",
    sample: "orina de 24 horas",
    method: "colorimetrico",
    price1: 25,
    price2: 15,
    tube: "galorena",
    info: "NO CONSUMIR ALCOHOL DURANTE TODO EL PROCESO DE RECOLECCIÓN. RECOLECCIÓN: ELIMINAR LA 1RA ORINA DE LA MAÑANA, RECOLECTAR DESDE LA 2DA EN ADELANTE HASTA EL DÍA SIGUIENTE DONDE SE RECOLECTA LA 1RA ORINA. NO ELIMINAR NI BOTAR NINGUNA MUESTRA DE ORINA. ANOTAR FECHA, INICIO Y TERMINO DE LA RECOLECCIÓN.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 97,
    name: "depuracion de creatinina en orina de 24 h",
    sample: "orina de 24 horas/suero",
    method: "cinetico",
    price1: 25,
    price2: 15,
    tube: "galorena/tubo rojo o amarillo",
    info: "NO CONSUMIR ALCOHOL DURANTE TODO EL PROCESO DE RECOLECCIÓN. RECOLECCIÓN: ELIMINAR LA 1RA ORINA DE LA MAÑANA, RECOLECTAR DESDE LA 2DA EN ADELANTE HASTA EL DÍA SIGUIENTE DONDE SE RECOLECTA LA 1RA ORINA. NO ELIMINAR NI BOTAR NINGUNA MUESTRA DE ORINA. ANOTAR FECHA, INICIO Y TERMINO DE LA RECOLECCIÓN.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 98,
    name: "hcg cuantificado",
    sample: "suero",
    method: "elisa",
    price1: 60,
    price2: 40,
    tube: "tubo rojo o amarillo",
    info: "no requiere ayuno previo",
    time: "2 horas",
    quantity: 1,
  },
  {
    id: 99,
    name: "hcg cualitativo",
    sample: "suero",
    method: "cromatografia",
    price1: 20,
    price2: 12,
    tube: "tubo rojo o amarillo",
    info: "no requiere ayuno previo",
    time: "30 minutos",
    quantity: 1,
  },
  {
    id: 100,
    name: "hierro serico",
    sample: "suero",
    method: "cinetico",
    price1: 45,
    price2: 35,
    tube: "tubo rojo o amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 101,
    name: "leptospira igm-igg",
    sample: "suero",
    method: "cromatografia",
    price1: 70,
    price2: 55,
    tube: "tubo rojo o amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "2 horas",
    quantity: 1,
  },
  {
    id: 102,
    name: "fosforo",
    sample: "suero",
    method: "cinetico",
    price1: 50,
    price2: 35,
    tube: "tubo rojo o amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 103,
    name: "magnesio",
    sample: "suero",
    method: "cinetico",
    price1: 45,
    price2: 35,
    tube: "tubo rojo o amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 104,
    name: "urocultivo más antibiograma",
    sample: "orina simple",
    method: "CULTIVO / MICROSCOPIA",
    price1: 50,
    price2: 20,
    tube: "frasco esteril",
    info: "COLECTAR LA MUESTRA EN FRASCO ESTÉRIL. NO ANTIBIOTICOS 03 DIAS PREVIOS AL nameEN. HIGIENE PREVIA DE LOS GENITALES. RECOLECTAR 1RA ORINA DE LA MAÑANA (ELIMINANDO EL 1ER CHORRO) Y REMITIR LA MUESTRA LO ANTES POSIBLE AL LABORATORIO (O MANTENER EN REFRIGERACIÓN 2 a 8°C HASTA SU ENVÍO)",
    time: "3 dias",
    quantity: 1,
  },
  {
    id: 105,
    name: "proteina c reactiva (pcr cuantificado)",
    sample: "suero",
    method: "inmunoflorescencia",
    price1: 50,
    price2: 35,
    tube: "tubo rojo o amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 106,
    name: "proteina c reactiva (pcr cualitativo)",
    sample: "suero",
    method: "turbidimetria",
    price1: 20,
    price2: 12,
    tube: "tubo rojo o amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 107,
    name: "factor reumatoideo (fr cualitativo)",
    sample: "suero",
    method: "turbidimetria",
    price1: 20,
    price2: 12,
    tube: "tubo rojo o amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 108,
    name: "antiestreptolisina (aso cualitativo)",
    sample: "suero",
    method: "turbidimetria",
    price1: 20,
    price2: 12,
    tube: "tubo rojo o amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 109,
    name: "hematocrito hto",
    sample: "sangre total",
    method: "manual",
    price1: 10,
    price2: 5,
    tube: "tubo lila",
    info: "no requiere preparacion previa",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 110,
    name: "bilirrubinas totales y fraccionadas",
    sample: "suero",
    method: "colorimetrico",
    price1: 20,
    price2: 15,
    tube: "tubo rojo / amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 111,
    name: "aglutinaciones febriles",
    sample: "suero",
    method: "aglutinacion/manual",
    price1: 25,
    price2: 15,
    tube: "tubo rojo / amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 112,
    name: "electrolitos sericos (cl, na, k)",
    sample: "suero",
    method: "potenciometria",
    price1: 65,
    price2: 45,
    tube: "tubo rojo / amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 113,
    name: "aga electrolitos",
    sample: "sangre arterial",
    method: "potenciometria",
    price1: 100,
    price2: 90,
    tube: "jeringa con heparina",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 114,
    name: "COCAINA PBC (ORINA SIMPLE) - CUALITATIVO",
    sample: "orina simple",
    method: "INMUNOCROMATOGRAFIA",
    price1: 45,
    price2: 35,
    tube: "FRASCO ORINA",
    info: "NO REQUIERE AYUNO Y/O PREPARACIÓN PREVIA. NOTA: ES RESPONSABILIDAD DE LA REFERENCIA; IDENTIFICAR Y CONSTATAR QUE LA ORINA PERTENECE AL PACIENTE. NO HABER INGERIDO MATE DE COCA 24 HORAS ANTES DEL nameEN. NO CONSUMIR MEDICACIÓN DEL TIPO DE ANTINFLAMATORIOS, POR LO MENOS 48 HORAS ANTES DEL nameEN.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 115,
    name: "MARIHUANA THC (ORINA SIMPLE) - CUALITATIVO",
    sample: "orina simple",
    method: "INMUNOCROMATOGRAFIA / MANUAL",
    price1: 45,
    price2: 35,
    tube: "FRASCO ORINA",
    info: "NO REQUIERE AYUNO Y/O PREPARACIÓN PREVIA. EL PACIENTE DEBERA PRESENTARSE CON DNI EN EL CASO DE MENORES DE EDAD CON LA PERSONA RESPONSABLE CON DNI Y FIRMAR FORMATO DE CONSENTIMIENTO PARA LA PRUEBA Y COLOCAR SU HUELLA DIGITAL, MUESTRA > 20 ML. ORINA REFRIGERADO. NOTA: ES RESPONSABILIDAD DE LA REFERENCIA; IDENTIFICAR Y CONSTATAR QUE LA ORINA PERTENECE AL PACIENTE.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 116,
    name: "ROTAVIRUS + ADENOVIRUS (HECES)",
    sample: "heces",
    method: "inmunocromatografia",
    price1: 50,
    price2: 35,
    tube: "FRASCO CON TAPA ROSCA",
    info: "MUESTRA FRESCA, LA QUE CONTENGA MOCO Y/O SANGRE. INFANTES: EL PAÑAL COLOCAR AL REVES, PARA EVITAR QUE EL GEL DEL PAÑAL ABSORBA LOS LIQUIDOS O QUE LAS HECES SE IMPREGNEN. REFRIGERAR, EN EL CASO DE NO ENVIAR INMEDIATAMENTE.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 117,
    name: "bk esputo directo",
    sample: "varios",
    method: "microscopia manual",
    price1: 35,
    price2: 15,
    tube: "FRASCO CON TAPA ROSCA",
    info: "NO REQUIERE DE PREPARACION PREVIA SEGÚN EL TIPO DE MUESTRA. SE SUGIERE OBTENER LA MUESTRA DE ESPUTO MUY TEMPRANO AL LEVANTARSE, ANTES DE CEPILLARSE LOS DIENTES, ANTES DE ENJUAGARSE LA BOCA Y ANTES DE INGERIR ALIMENTOS. SE DEBE RECOLECTAR LA EXPECTORACION BRONQUIAL,SIN SALIVA.",
    time: "1 día",
    quantity: 1,
  },
  {
    id: 118,
    name: "cultivo de secrecion vaginal",
    sample: "secrecion vaginal",
    method: "CULTIVO / MICROSCOPIA / MANUAL",
    price1: 50,
    price2: 20,
    tube: "MEDIO DE TRANSPORTE",
    info: "NO ANTIBIÓICOS, NI OVULOS 3 DIAS ANTES DEL EXÁMEN Y SIN ASEO PREVIO, MEDIO DE TRANSPORTE + 02 LAMINAS (FROTIS) INCLUYE : nameEN DIRECTO + ANTIBIOGRAMA",
    time: "3 dias",
    quantity: 1,
  },
  {
    id: 119,
    name: "cultivo herida",
    sample: "herida",
    method: "CULTIVO / MICROSCOPIA / MANUAL",
    price1: 50,
    price2: 20,
    tube: "MEDIO DE TRANSPORTE",
    info: "NO ANTIBIÓTICOS 3 DIAS ANTES DE LA PRUEBA, NI APLICACIÓN DE ANTISEPTICAS. HERIDAS: SI ES NECESARIO LIMPIAR CON SUERO FISIOLOG. Y/O TOMAR LA MUESTRA DE LA PARTE INTERNA DE LA HERIDA. (MEDIO DE TRANSPORTE + 02 LAMINAS (FROTIS) ) ASPIRADOS: ENVIAR LA MUESTRA EN EL MISMO FRASCO O JERINGA QUE SE TOMÓ. NOTA: ES IMPORTANTE QUE SE INDIQUE LA UBICACIÓN Y TIPO DE MUESTRA QUE SE TOME EN LA ORDEN O TICKET. TIEMPO DE RESPUESTA NO SE INCLUYE DOMINGOS NI FERIADOS.",
    time: "3 dias",
    quantity: 1,
  },
  {
    id: 120,
    name: "hemocultivo con removedor de antibiotico",
    sample: "sangre total",
    method: "CULTIVO / MICROSCOPIA / MANUAL",
    price1: 90,
    price2: 65,
    tube: "frasco hemocultivo con removedor de antibiotico",
    info: "DE PREFERENCIA NO ANTIBIOTICOS, 03 DIAS PREVIOS AL nameEN. REVISAR SOLICITUD MÉDICA Y PRECISAR LUGAR DE PUNCIÓN EN EL FRASCO DE HEMOCULTIVO. INCLUYE REMOVEDOR DE ATB, MEDIO ADULTOS: 5-10 ML DE SANGRE TOTAL (VENOSA), MEDIO PEDIATRICO: INFANTES: 1-2 ML Y NIÑOS: 3-5 ML DE SANGRE TOTAL (VENOSA).",
    time: "7 dias",
    quantity: 1,
  },
  {
    id: 121,
    name: "tiempo de coagulacion y tiempo de sangria",
    sample: "sangre total",
    method: "manual",
    price1: 10,
    price2: 5,
    tube: "sin aditivo",
    info: "no requiere ayuna.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 122,
    name: "transaminasa tgo",
    sample: "suero",
    method: "cinetico",
    price1: 15,
    price2: 8,
    tube: "tubo rojo / amarillo",
    info: "Se recomienda ayuno de 8 horas.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 123,
    name: "transaminasa tgp",
    sample: "suero",
    method: "cinetico",
    price1: 15,
    price2: 8,
    tube: "tubo rojo / amarillo",
    info: "Se recomienda ayuno de 8 horas.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 124,
    name: "fosfatasa alcalina",
    sample: "suero",
    method: "cinetico",
    price1: 15,
    price2: 8,
    tube: "tubo rojo / amarillo",
    info: "Se recomienda ayuno de 8 horas.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 125,
    name: "proteinas totales y fraccionadas",
    sample: "suero",
    method: "colorimetrico",
    price1: 15,
    price2: 12,
    tube: "tubo rojo / amarillo",
    info: "Se recomienda ayuno de 8 horas.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 126,
    name: "ca 19-9",
    sample: "suero",
    method: "quimioluminiscencia",
    price1: 60,
    price2: 45,
    tube: "tubo rojo / amarillo",
    info: "Se recomienda ayuno de 8 horas.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 127,
    name: "velocidad de sedimentacion glovular(vsg)",
    sample: "sangre total",
    method: "manual",
    price1: 10,
    price2: 5,
    tube: "tubo lila",
    info: "No necesita ayuno previo.",
    time: "2 horas",
    quantity: 1,
  },
  {
    id: 128,
    name: "gota gruesa en lamina",
    sample: "sangre total",
    method: "manual/coloracion giensa",
    price1: 15,
    price2: 10,
    tube: "tubo lila más lamina",
    info: "No necesita ayuno previo.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 129,
    name: "prueba cruzada",
    sample: "suero",
    method: "manual",
    price1: 35,
    price2: 30,
    tube: "tubo rojo/amarillo",
    info: "No necesita ayuno previo.",
    time: "2 horas",
    quantity: 1,
  },
  {
    id: 130,
    name: "secrecion directa mas gram",
    sample: "secrecion",
    method: "microscopia manual",
    price1: 15,
    price2: 12,
    tube: "tubo con solucion salina más lamina",
    info: "No aseo previo.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 131,
    name: "dengue igg-igm-ns1",
    sample: "suero",
    method: "inmunocromatografia",
    price1: 60,
    price2: 40,
    tube: "tubo rojo ó amarillo",
    info: "No requiere ayuno previo.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 132,
    name: "deshidrogenasa lactica-dhl",
    sample: "suero",
    method: "cinetico",
    price1: 45,
    price2: 25,
    tube: "tubo rojo ó amarillo",
    info: "Se recomienda ayuno de 8 horas.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 133,
    name: "raspado de piel directo-koh hongos-acaros",
    sample: "raspado de piel",
    method: "microscopia/manual",
    price1: 30,
    price2: 15,
    tube: "placa petri pequeña",
    info: "SUSPENDER ANTIMICÓTICOS (ORALES, CREMAS, SOLUCIONES)5 DÍAS PREVIOS AL nameEN, NO REALIZAR BAÑO PREVIO O ASEO DE LA ZONA AFECTADA.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 134,
    name: "cultivo de hongos",
    sample: "una, piel, cuero cabelludo, orina",
    method: "cultivo/microscopia/manual",
    price1: 60,
    price2: 40,
    tube: "placa petri pequeña",
    info: "NO ANTIMICÓTICOS (ORALES, CREMAS O SOLUCIONES) POR 03 DIAS ANTES DE LA PRUEBA, NO ASEO DE LA ZONA AFECTADA. EN CULTIVOS DE UÑAS, DEJAR QUE ESTAS CREZCAN PARA LA OBTENCIÓN DE UNA MEJOR MUESTRA. EN EL CASO DE AUSENCIA O ESCASAS ESCAMAS (PIEL), ENVIAR EL BISTURÍ CON EL CUAL SE HIZO EL RASPADO. INDICAR LA ZONA AFECTADA Y EL TIPO DE MUESTRA EN LA ORDEN O TICKET.",
    time: "7 dias",
    quantity: 1,
  },
  {
    id: 135,
    name: "herpes 2 (igg)",
    sample: "suero",
    method: "quimiolumiscencia",
    price1: 80,
    price2: 55,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "2 horas",
    quantity: 1,
  },
  {
    id: 136,
    name: "troponina t",
    sample: "suero",
    method: "quimiolumiscencia",
    price1: 60,
    price2: 50,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "2 hora",
    quantity: 1,
  },
  {
    id: 137,
    name: "estradiol libre",
    sample: "suero",
    method: "electroquimioluminiscencia",
    price1: 230,
    price2: 210,
    tube: "tapa rojo ó amarillo",
    info: "se sugiere ayuno de 8 hras",
    time: "13 dias",
    quantity: 1,
  },
  {
    id: 138,
    name: "complemento c3-c4",
    sample: "suero",
    method: "electroquimioluminiscencia",
    price1: 150,
    price2: 140,
    tube: "tapa rojo ó amarillo",
    info: "se sugiere ayuno de 8 hras",
    time: "6 dias",
    quantity: 1,
  },
  {
    id: 139,
    name: "ENA - PERFIL AUTOINMUNE",
    sample: "suero",
    method: "---",
    price1: 320,
    price2: 300,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS. PERFIL INCLUYE: NRNP/SM, SM, SS-A, SS-B, SCL70, JO-1, DNADS, HISTONAS, PROTEINA P-RIBOSOMAL, M2, NUCLEOSOMAS. PM-SCL, CENTROMERO.",
    time: "7 dias",
    quantity: 1,
  },
  {
    id: 140,
    name: "cloro serico (cl)",
    sample: "suero",
    method: "colorimetrico",
    price1: 40,
    price2: 30,
    tube: "tubo rojo / amarillo",
    info: "Se recomienda ayuno de 8 horas.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 141,
    name: "sodio serico (na)",
    sample: "suero",
    method: "colorimetrico",
    price1: 40,
    price2: 30,
    tube: "tubo rojo / amarillo",
    info: "Se recomienda ayuno de 8 horas.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 142,
    name: "potasio serico (k)",
    sample: "suero",
    method: "colorimetrico",
    price1: 45,
    price2: 25,
    tube: "tubo rojo / amarillo",
    info: "Se recomienda ayuno de 8 horas.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 143,
    name: "perfil reumatoideo(fr-aso-pcr)",
    sample: "suero",
    method: "inmunoturbidimetria",
    price1: 50,
    price2: 36,
    tube: "tubo rojo / amarillo",
    info: "Se recomienda ayuno de 8 horas.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 144,
    name: "coprocultivo mas antibiograma",
    sample: "heces",
    method: "cultivo",
    price1: 50,
    price2: 25,
    tube: "frasco tapa rosca boca ancha",
    info: "COLECTAR LA MUESTRA EN FRASCO boca ancha tapa rosca. NO ANTIBIOTICOS 03 DIAS PREVIOS AL nameEN. REMITIR LA MUESTRA LO ANTES POSIBLE AL LABORATORIO (O MANTENER EN REFRIGERACIÓN 2 a 8°C HASTA SU ENVÍO).",
    time: "3 dias",
    quantity: 1,
  },
  {
    id: 145,
    name: "BNP (PEPTIDO NATRIUREICO)",
    sample: "suero",
    method: "INMUNOQUIMIOLUMINISCENCIA",
    price1: 150,
    price2: 110,
    tube: "tapa dorada",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "3 HORAS",
    quantity: 1,
  },
  {
    id: 146,
    name: "HELICOBACTER PYLORI, TEST DE ALIENTO - CARBONO 13 (TEST UREASA)",
    sample: "aliento",
    method: "Espectometría infrarrojo (C13)",
    price1: 230,
    price2: 220,
    tube: "bolsa metalica",
    info: "NO REQUIERE CITA PREVIA. RECOMENDABLE EN AYUNAS SIN CEPILLARSE LOS DIENTES EL DÍA DE LA PRUEBA, CASO ESPECIAL: NO INGERIR ALIMENTOS MÍNIMO 3 HORAS ANTES. MEDICINAS: NO ANTIBIÓTICOS, BISMUTOL O PEPTOBISMOL POR 4 SEMANAS. NO ANTIÁCIDOS POR 2 SEMANAS (OMEPRAZOL O DERIVADOS).",
    time: "2 HORAS",
    quantity: 1,
  },
  {
    id: 147,
    name: "PAPANICOLAOU",
    sample: "varios",
    method: "MICROSCOPIA / MANUAL",
    price1: 45,
    price2: 20,
    tube: "lamina",
    info: "NO REQUIERE AYUNO Y/O PREPARACIÓN PREVIA. ABSTINENCIA SEXUAL 3 DIAS ANTES, NO OVULOS NI CREMAS VAGINALES. NO ESTAR EN EL PERIODO MENSTRUAL. ENVIAR 2 LÁMINAS FIJADAS, ROTULADAS Y PROTEGIDAS",
    time: "6 Días",
    quantity: 1,
  },
  {
    id: 148,
    name: "test de ada",
    sample: "liquido varios/suero",
    method: "colorimetrico",
    price1: 60,
    price2: 40,
    tube: "envase esteril/tubo rojo",
    info: "no requiere ayuno",
    time: "1 día",
    quantity: 1,
  },
  {
    id: 149,
    name: "helicobacter pylori total(prueba rapida)",
    sample: "suero",
    method: "cromatografia",
    price1: 35,
    price2: 28,
    tube: "tubo rojo",
    info: "se recomienda ayuno de 8 horas.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 150,
    name: "helicobacter pylori igm",
    sample: "suero",
    method: "quimioluminiscencia",
    price1: 60,
    price2: 40,
    tube: "tubo rojo",
    info: "se recomienda ayuno de 8 horas.",
    time: "3 horas",
    quantity: 1,
  },
  {
    id: 151,
    name: "citomegalovirus igm",
    sample: "suero",
    method: "quimioluminiscencia ",
    price1: 60,
    price2: 40,
    tube: "tubo rojo",
    info: "se recomienda ayuno de 8 horas.",
    time: "día",
    quantity: 1,
  },
  {
    id: 152,
    name: "citomegalovirus igg",
    sample: "suero",
    method: "quimioluminiscencia ",
    price1: 60,
    price2: 40,
    tube: "tubo rojo",
    info: "se recomienda ayuno de 8 horas.",
    time: "1 día",
    quantity: 1,
  },
  {
    id: 153,
    name: "rubeola igg",
    sample: "suero",
    method: "quimioluminiscencia ",
    price1: 60,
    price2: 40,
    tube: "tubo rojo",
    info: "se recomienda ayuno de 8 horas.",
    time: "1 día",
    quantity: 1,
  },
  {
    id: 154,
    name: "rubeola igm",
    sample: "suero",
    method: "quimioluminiscencia ",
    price1: 60,
    price2: 40,
    tube: "tubo rojo",
    info: "se recomienda ayuno de 8 horas.",
    time: "1 día",
    quantity: 1,
  },
  {
    id: 155,
    name: "toxoplasma igg",
    sample: "suero",
    method: "quimioluminiscencia ",
    price1: 80,
    price2: 55,
    tube: "tubo rojo",
    info: "se recomienda ayuno de 8 horas.",
    time: "1 día",
    quantity: 1,
  },
  {
    id: 156,
    name: "toxoplasma igm",
    sample: "suero",
    method: "quimioluminiscencia ",
    price1: 80,
    price2: 55,
    tube: "tubo rojo",
    info: "se recomienda ayuno de 8 horas.",
    time: "1 día",
    quantity: 1,
  },
  {
    id: 157,
    name: "creatinina en orina de 24 h",
    sample: "orina de 24 h",
    method: "cinetico",
    price1: 15,
    price2: 10,
    tube: "frasco tapa rosca",
    info: "NO CONSUMIR ALCOHOL DURANTE TODO EL PROCESO DE RECOLECCIÓN. RECOLECCIÓN: ELIMINAR LA 1RA ORINA DE LA MAÑANA, RECOLECTAR DESDE LA 2DA EN ADELANTE HASTA EL DÍA SIGUIENTE DONDE SE RECOLECTA LA 1RA ORINA. NO ELIMINAR NI BOTAR NINGUNA MUESTRA DE ORINA. ANOTAR FECHA, INICIO Y TERMINO DE LA RECOLECCIÓN.",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 158,
    name: "rosa de bengala",
    sample: "suero",
    method: "aglutinacion",
    price1: 50,
    price2: 40,
    tube: "rojo/amarillo",
    info: "no requiere ayuno previo",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 159,
    name: "t3",
    sample: "suero",
    method: "quimioluminiscencia",
    price1: 60,
    price2: 40,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 160,
    name: "albumina",
    sample: "suero",
    method: "colorimetrico",
    price1: 10,
    price2: 6,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 161,
    name: "vitamina d total 25-hidroxivitamina d (d2+d3)",
    sample: "suero",
    method: "quimioluminiscencia ",
    price1: 250,
    price2: 240,
    tube: "tapa rojo ó amarillo",
    info: "se recomienda ayuno de 8 horas",
    time: "6 dias",
    quantity: 1,
  },
  {
    id: 162,
    name: "fibrinogeno",
    sample: "plasma",
    method: "coagulometria",
    price1: 40,
    price2: 35,
    tube: "tapa celeste",
    info: "No es necesario estar en ayunas",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 163,
    name: "cultivo de secreción faringea",
    sample: "secreción fraringe",
    method: "CULTIVO / MICROSCOPIA / MANUAL",
    price1: 50,
    price2: 30,
    tube: "tubo esteril de vidrio + lamina",
    info: "EN AYUNAS, NO ASEO BUCAL, NI INGESTA DE LIQUIDOS NI SOLUCIONES DESINFECTANTES. NO ANTIBIÓTICOS 3 DIAS ANTES DEL EXÁMEN.",
    time: "4 días",
    quantity: 1,
  },
  {
    id: 164,
    name: "recuento de hematies",
    sample: "sangre total",
    method: "manual",
    price1: 15,
    price2: 10,
    tube: "tubo lila",
    info: "no requiere ayuno previo",
    time: "1 hora",
    quantity: 1,
  },
  {
    id: 165,
    name: "chagas",
    sample: "suero",
    method: "quimioluminiscencia",
    price1: 60,
    price2: 48,
    tube: "tubo rojo ó amarillo",
    info: "se sugiere ayuno de 8 horas",
    time: "1 día",
    quantity: 1,
  },
  {
    id: 166,
    name: "cultivo de herida",
    sample: "secre. herida",
    method: "CULTIVO / MICROSCOPIA / MANUAL",
    price1: 50,
    price2: 30,
    tube: "MEDIO DE TRANSPORTE + 02 LAMINAS (FROTIS) INCLUYE: DIRECTO + ANTIBIOGRAMA",
    info: "NO ANTIBIÓTICOS 3 DIAS ANTES DEL EXÁMEN, NI ASEO PREVIO.",
    time: "4 días aprox.",
    quantity: 1,
  },
  {
    id: 167,
    name: "DESPISTAJE ALERGICO AMPLIADO (295 ALERGENOS)",
    sample: "suero",
    method: "MICROARRAY / ALEX2",
    price1: 1100,
    price2: 1100,
    tube: "tubo rojo ó amarillo",
    info: "NO ES NECESARIO EL AYUNO NI LA SUSPENCIÓN DE MEDICAMENTOS (ANTIHISTAMÍNICOS, INHALADORES, ANTILEUCOTRIENOS, CORTICOIDES, ETC). SE REALIZA EL DOSAJE DE INMUGLOBULINA IGE PARA CADA ALERGENO.",
    time: "7 días aprox.",
    quantity: 1,
  },
  {
    id: 168,
    name: "DESPISTAJE ALERGICO BASICO (36 ALERGENOS)",
    sample: "suero",
    method: "MICROARRAY / ALEX2",
    price1: 320,
    price2: 260,
    tube: "tubo rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS. LA PRUEBA DETERMINA 36 TIPOS DIFERENTES DE ALERGENOS (NO INCLUYE MEDICAMENTOS). INCLUYE: ALIMENTOS, ANIMALES, POLEN, PLANTAS E INSECTOS. SE REALIZA EL DOSAJE DE INMUGLOBULINA IGE PARA CADA ALERGENO.",
    time: "5 días aprox.",
    quantity: 1,
  },
  {
    id: 169,
    name: "perfil reumatoideo cuantificado",
    sample: "suero",
    method: "inmunoflorescencia",
    price1: 60,
    price2: 60,
    tube: "tubo rojo ó amarillo",
    info: "no requiere ayuno previo.",
    time: "2 horas.",
    quantity: 1,
  },
  {
    id: 170,
    name: "dhea-s",
    sample: "suero",
    method: "elisa",
    price1: 70,
    price2: 50,
    tube: "tubo rojo ó amarillo",
    info: "no requiere ayuno previo.",
    time: "2 horas.",
    quantity: 1,
  },
  {
    id: 171,
    name: "acth",
    sample: "plasma",
    method: "elisa",
    price1: 80,
    price2: 55,
    tube: "tubo lila",
    info: "no requiere ayuno previo.",
    time: "2 horas.",
    quantity: 1,
  },
  {
    id: 172,
    name: "mioglobina",
    sample: "suero",
    method: "clia",
    price1: 80,
    price2: 55,
    tube: "tubo rojo ó amarillo",
    info: "no requiere ayuno previo.",
    time: "2 horas.",
    quantity: 1,
  },
  {
    id: 173,
    name: "block cell-biopsia",
    sample:
      "MUESTRAS FRESCAS (LIQ. SINOVIAL, PLEURAL, ASCITICO, ETC), TOMADAS POR MEDICO TRATANTE. ORDEN MÉDICA OBLIGATORIA.",
    method: "microscopia/manual",
    price1: 140,
    price2: 90,
    tube: "FRASCO ESTERIL",
    info: "MUESTRAS FRESCAS (LIQ. SINOVIAL, PLEURAL, ASCITICO, ETC), TOMADAS POR MEDICO TRATANTE. TRANSPORTAR MUESTRAS A LA BREVEDAD POSIBLE Y EN CADENA DE FRÍO. SE REQUIERE MÍNIMO 60ML PARA UN BUEN REPORTE.",
    time: "7 dias aprox.",
    quantity: 1,
  },
  {
    id: 174,
    name: "citoquimico-liquido",
    sample:
      "MUESTRAS FRESCAS (LIQ. SINOVIAL, PLEURAL, ASCITICO, ETC), TOMADAS POR MEDICO TRATANTE. ORDEN MÉDICA OBLIGATORIA.",
    method: "citoquimico/manual",
    price1: 60,
    price2: 35,
    tube: "FRASCO ESTERIL",
    info: "DEBE SER UNA MUESTRA TOMADA POR EL MÉDICO TRATANTE (PARACENTESIS), TODA MUESTRA CON PRESENCIA DE COÁGULO Y/O LIQUIDOS HEMORRAGICOS SERAN RECHAZADAS.",
    time: "1 dia",
    quantity: 1,
  },
  {
    id: 175,
    name: "herpes 2 (igm)",
    sample: "suero",
    method: "quimiolumiscencia",
    price1: 80,
    price2: 55,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "2 horas",
    quantity: 1,
  },
  {
    id: 176,
    name: "ACIDOS BILIARES laboratorio roe (lima)",
    sample: "suero",
    method: "bioquimico",
    price1: 380,
    price2: 330,
    tube: "tapa rojo ó amarillo",
    info: "SE RECOMIENDA AYUNO DE 8 HORAS ANTES DE LA PRUEBA.",
    time: "5 dias",
    quantity: 1,
  },
  {
    id: 177,
    name: "cultivo de semen ",
    sample: "semen",
    method: "cultivo",
    price1: 45,
    price2: 20,
    tube: "frasco esteril tapa verde",
    info: "COLECTAR LA MUESTRA EN FRASCO ESTÉRIL. NO ANTIBIOTICOS 03 DIAS PREVIOS AL examen. HIGIENE PREVIA DE LOS GENITALES, REMITIR LA MUESTRA LO ANTES POSIBLE AL LABORATORIO (O MANTENER EN REFRIGERACIÓN 2 a 8°C HASTA SU ENVÍO)",
    time: "3 dias",
    quantity: 1,
  },
];

urocultivo